const REQUEST_TOKEN_LOCATION = "x-access-token";
const JWT_SIGN_KEY = "supersecretjwtsigningkey@220489799";

const HISTORY_TYPE = {
  NEW_USER_SIGN_UP: 'NEW_USER_SIGN_UP',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  COMMENT_ADDED_ON_TICKET: 'COMMENT_ADDED_ON_TICKET',
  REPLIED_ON_A_COMMENT: 'REPLIED_ON_A_COMMENT'
}
module.exports = {
  REQUEST_TOKEN_LOCATION,
  JWT_SIGN_KEY,
  HISTORY_TYPE
};
